-- 2026-09-11 · Estrategia de Precios · segundo paso del drill del SKU
--
--   1. precios_competencia   — referencias de precio de la competencia por SKU (captura manual desde el drill).
--   2. elasticidad_supuestos — elasticidad supuesta por categoría (default −1.2) para el simulador cuando el SKU
--                              ni su categoría tienen elasticidad calculada desde precios_historico.
--   3. v_precios_cambios     — TODOS los cambios de precio por sku+lista (mes vs mes anterior con dato) a partir
--                              de precios_historico; complementa a v_precios_cambios_mes (que sólo trae el último).
--                              Es la base de la elasticidad por cambio de precio (cálculo en precios/elasticidad.js).
--
-- RLS: lectura authenticated; escritura sólo perfiles internos o super admin (patrón de forecast_snapshots).
-- Auditoría: trg_auditoria (fn_auditoria) si la función existe.

-- ─── 1. precios_competencia ──────────────────────────────────────────────────
create table if not exists public.precios_competencia (
  id               bigint generated by default as identity primary key,
  sku              text        not null,
  competidor       text        not null,
  marca            text,
  modelo           text,
  especificaciones text,
  precio           numeric     not null check (precio >= 0),
  moneda           text        not null default 'MXN',
  fuente           text,
  url              text,
  fecha            date        not null default current_date,
  comentario       text,
  creado_por       uuid        default auth.uid(),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
comment on table public.precios_competencia is
  'Precios de la competencia por SKU (competidor · marca/modelo · precio sin IVA · fecha). Captura manual desde el drill de Estrategia de Precios.';
create index if not exists precios_competencia_sku_idx on public.precios_competencia (sku, fecha desc);

alter table public.precios_competencia enable row level security;

drop policy if exists precios_competencia_read on public.precios_competencia;
create policy precios_competencia_read on public.precios_competencia
  for select to authenticated using (true);

drop policy if exists precios_competencia_insert on public.precios_competencia;
create policy precios_competencia_insert on public.precios_competencia
  for insert to authenticated
  with check (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ));

drop policy if exists precios_competencia_update on public.precios_competencia;
create policy precios_competencia_update on public.precios_competencia
  for update to authenticated
  using (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ))
  with check (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ));

drop policy if exists precios_competencia_delete on public.precios_competencia;
create policy precios_competencia_delete on public.precios_competencia
  for delete to authenticated
  using (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ));

grant select, insert, update, delete on public.precios_competencia to authenticated;
grant usage, select on sequence public.precios_competencia_id_seq to authenticated;
grant select on public.precios_competencia to anon;

-- updated_at automático
create or replace function public.fn_precios_competencia_touch() returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists trg_precios_competencia_touch on public.precios_competencia;
create trigger trg_precios_competencia_touch before update on public.precios_competencia
  for each row execute function public.fn_precios_competencia_touch();

-- ─── 2. elasticidad_supuestos ────────────────────────────────────────────────
create table if not exists public.elasticidad_supuestos (
  categoria   text        primary key,
  elasticidad numeric     not null default -1.2,
  updated_at  timestamptz not null default now(),
  updated_by  uuid        default auth.uid()
);
comment on table public.elasticidad_supuestos is
  'Elasticidad precio-demanda SUPUESTA por categoría (Δpz% / Δprecio%, default −1.2). La usa el simulador del drill cuando ni el SKU ni su categoría tienen elasticidad calculada.';

alter table public.elasticidad_supuestos enable row level security;

drop policy if exists elasticidad_supuestos_read on public.elasticidad_supuestos;
create policy elasticidad_supuestos_read on public.elasticidad_supuestos
  for select to authenticated using (true);

drop policy if exists elasticidad_supuestos_insert on public.elasticidad_supuestos;
create policy elasticidad_supuestos_insert on public.elasticidad_supuestos
  for insert to authenticated
  with check (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ));

drop policy if exists elasticidad_supuestos_update on public.elasticidad_supuestos;
create policy elasticidad_supuestos_update on public.elasticidad_supuestos
  for update to authenticated
  using (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ))
  with check (exists (
    select 1 from public.perfiles p
    where p.user_id = auth.uid() and (p.tipo = 'interno' or coalesce(p.es_super_admin, false))
  ));

grant select, insert, update on public.elasticidad_supuestos to authenticated;
grant select on public.elasticidad_supuestos to anon;

-- ─── Auditoría (mismo patrón que 20260910_auditoria_cambios.sql) ───
do $$
begin
  if to_regprocedure('public.fn_auditoria()') is not null then
    execute 'drop trigger if exists trg_auditoria on public.precios_competencia';
    execute 'create trigger trg_auditoria after insert or update or delete on public.precios_competencia for each row execute function public.fn_auditoria(''id'')';
    execute 'drop trigger if exists trg_auditoria on public.elasticidad_supuestos';
    execute 'create trigger trg_auditoria after insert or update or delete on public.elasticidad_supuestos for each row execute function public.fn_auditoria(''categoria'')';
  else
    raise notice 'fn_auditoria() no existe: precios_competencia / elasticidad_supuestos sin auditoría';
  end if;
end $$;

-- ─── 3. v_precios_cambios · todos los cambios de precio (sku, lista, mes) ────
-- Una fila por cada mes en que el precio de (sku, lista) difiere del mes anterior con dato.
-- Con un solo mes de histórico la vista está vacía (el histórico acumula desde 2026-09-11).
create or replace view public.v_precios_cambios
with (security_invoker = true) as
select x.sku, x.lista, x.anio, x.mes,
       x.precio      as precio_nuevo,
       x.precio_prev as precio_anterior,
       x.anio_prev, x.mes_prev,
       case when x.precio_prev = 0 then null
            else round((x.precio - x.precio_prev) / x.precio_prev * 100, 2) end as delta_pct
  from (
    select h.sku, h.lista, h.anio, h.mes, h.precio,
           lag(h.precio) over w as precio_prev,
           lag(h.anio)   over w as anio_prev,
           lag(h.mes)    over w as mes_prev
      from public.precios_historico h
    window w as (partition by h.sku, h.lista order by h.anio, h.mes)
  ) x
 where x.precio_prev is not null and x.precio <> x.precio_prev;
comment on view public.v_precios_cambios is
  'Todos los cambios de precio por sku+lista+mes desde precios_historico (base de la elasticidad por cambio de precio).';
grant select on public.v_precios_cambios to authenticated, service_role;
